build:
  image: armhfbuild/golang:1.5.3
  environment:
    - GO15VENDOREXPERIMENT=1
  commands:
    - mkdir -p github.com/drone
    - git clone https://github.com/drone/drone-cli /drone/src/github.com/drone/drone-cli
    - grep -lr drone/drone-exec:latest /drone/src/github.com/drone/drone-cli | xargs sed -i 's/drone\/drone\-exec:latest/armhfbuild\/drone-exec:latest/'
    - GOOS=linux   GOARCH=arm   go build -o ./bin/linux_arm/drone     github.com/drone/drone-cli/drone
